export const connectPageStyles = {
  root: {
    position: "fixed",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    background: "#F5F5F7",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    zIndex: 9999,
    overflow: "auto",
    padding: "32px 16px",
    minHeight: "100vh",
  },
  card: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    width: "100%",
    maxWidth: "1100px",
    minHeight: "72vh",
    background: "#ffffff",
    borderRadius: "20px",
    boxShadow: "0 4px 32px rgba(0,0,0,0.08), 0 1px 4px rgba(0,0,0,0.04)",
    overflow: "hidden",
    border: "1px solid #e5e7eb",
  },
  formSide: {
    display: "flex",
    flexDirection: "column",
    padding: "48px",
    paddingTop: "56px",
    position: "relative",
    zIndex: 10,
    boxSizing: "border-box",
    background: "#ffffff",
  },
  formBlob1: {
    position: "absolute",
    top: "-60px",
    left: "10%",
    width: "280px",
    height: "280px",
    borderRadius: "50%",
    background: "linear-gradient(to bottom, #3b82f6, #a5f3fc)",
    opacity: 0.08,
    pointerEvents: "none",
    filter: "blur(80px)",
  },
  formBlob2: {
    position: "absolute",
    top: "20px",
    right: "-30px",
    width: "240px",
    height: "240px",
    borderRadius: "50%",
    background: "linear-gradient(to bottom, #8b5cf6, #c4b5fd)",
    opacity: 0.07,
    pointerEvents: "none",
    filter: "blur(80px)",
  },
  headerWrapper: { marginBottom: "32px" },
  heading: {
    fontSize: "28px",
    fontWeight: 700,
    color: "#111827",
    margin: "0 0 4px",
    letterSpacing: "-0.4px",
    lineHeight: 1.25,
  },
  subheading: {
    fontSize: "15px",
    fontWeight: 400,
    color: "#6b7280",
    margin: "0",
    lineHeight: 1.5,
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    maxWidth: "420px",
    width: "100%",
  },
  googleBtn: (disabled) => ({
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    background: "#ffffff",
    color: "#374151",
    padding: "12px 16px",
    fontSize: "14px",
    fontWeight: 500,
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.65 : 1,
    transition: "background 0.2s, box-shadow 0.2s",
    marginBottom: "16px",
    boxSizing: "border-box",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  }),
  dividerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    marginBottom: "16px",
  },
  dividerLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: "1px",
    background: "#e5e7eb",
  },
  dividerText: {
    position: "relative",
    background: "#ffffff",
    padding: "0 12px",
    fontSize: "12px",
    color: "#9ca3af",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    marginBottom: "20px",
  },
  fieldWrap: { display: "flex", flexDirection: "column" },
  label: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#374151",
    marginBottom: "6px",
    display: "block",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "11px 14px",
    fontSize: "14px",
    color: "#111827",
    background: "#f9fafb",
    outline: "none",
    transition: "border-color 0.2s, background 0.2s",
    fontFamily: "inherit",
  },
  passwordWrap: { position: "relative" },
  passwordInput: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #e5e7eb",
    borderRadius: "10px",
    padding: "11px 44px 11px 14px",
    fontSize: "14px",
    color: "#111827",
    background: "#f9fafb",
    outline: "none",
    transition: "border-color 0.2s",
    fontFamily: "inherit",
  },
  eyeBtn: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    padding: "4px",
  },
  submitBtn: (loading) => ({
    width: "100%",
    border: "none",
    borderRadius: "10px",
    background: loading ? "#93c5fd" : "#2563eb",
    color: "#ffffff",
    padding: "12px 16px",
    fontSize: "14px",
    fontWeight: 600,
    cursor: loading ? "not-allowed" : "pointer",
    opacity: 1,
    transition: "background 0.2s, box-shadow 0.2s",
    boxSizing: "border-box",
    boxShadow: loading ? "none" : "0 4px 12px rgba(37,99,235,0.25)",
  }),
  errorBox: { fontSize: "12px", color: "#ef4444", marginTop: "6px" },
  footerSection: { marginTop: "auto", paddingTop: "28px", width: "100%" },
  footerText: {
    textAlign: "center",
    fontSize: "13px",
    color: "#9ca3af",
    lineHeight: 1.5,
  },
  footerLink: {
    color: "#6b7280",
    fontWeight: 500,
    textDecoration: "none",
    cursor: "pointer",
  },
  switchTextWrap: { marginTop: "14px", fontSize: "14px", color: "#6b7280", textAlign: "center" },
  switchBtn: {
    color: "#2563eb",
    border: "none",
    background: "none",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
    marginLeft: "4px",
  },
  gallerySide: {
    position: "relative",
    width: "100%",
    background: "#F0F4FF",
    display: "flex",
    justifyContent: "center",
    overflow: "hidden",
  },
  galleryGlow: {
    position: "absolute",
    bottom: "0",
    left: "50%",
    transform: "translateX(-50%)",
    width: "384px",
    height: "384px",
    opacity: 0.25,
    background: "linear-gradient(to bottom, #3b82f6, #a5f3fc)",
    borderRadius: "50%",
    filter: "blur(100px)",
    pointerEvents: "none",
    zIndex: 0,
  },
  galleryContainer: { display: "flex", gap: "8px", zIndex: 10, padding: "16px 16px 0 16px" },
  galleryColumn: { display: "flex", flexDirection: "column", gap: "8px", flex: 1 },
  galleryImage: { width: "100%", borderRadius: "12px", objectFit: "cover" },
  galleryFadeTop: {
    position: "absolute",
    inset: "auto 0 0 0",
    height: "60px",
    background: "linear-gradient(to top, #F0F4FF, rgba(240,244,255,0.8), transparent)",
    pointerEvents: "none",
    zIndex: 20,
  },
  pageFadeBottom: {
    pointerEvents: "none",
    position: "absolute",
    inset: "auto 0 0 0",
    height: "64px",
    background: "linear-gradient(to top, #F5F5F7, rgba(245,245,247,0.85), transparent)",
  },
};
